string = input('Digite algo: ')
print('O tipo primitivo desse valor é {}' .format(type(string)))
print('Só tem espaços? {}' .format(string.isspace()))
print('É um número? {}' .format(string.isnumeric()))
print('É alfabético? {}' .format(string.isalpha()))
print('É aflanumérico? {}' .format(string.isalnum()))
print('Está em maiúsculas? {}' .format(string.isupper()))
print('Está em minúsculas? {}' .format(string.islower()))
print('Está capitalizada? {}' .format(string.istitle()))